# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ai-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerstorage01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb6b9a42580b4418bd33b204cb6d0d73 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_71e645908d4247778766dcbc428c07ab }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerstorage01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fb6b9a42580b4418bd33b204cb6d0d73 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ai-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_edff79b39a39474ebdc1be2568279725 }}
        images: 'containerstorage01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fb6b9a42580b4418bd33b204cb6d0d73 }}/backend:${{ github.sha }}'