# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ai-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerstorage01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_854ca6a35c1f451d86a13e92ccd02805 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f14ef7aa846842bdbf7f3947cb066dbc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerstorage01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_854ca6a35c1f451d86a13e92ccd02805 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ai-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_32e4f1b49adb4dc2ad91fc8db57a5bd9 }}
        images: 'containerstorage01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_854ca6a35c1f451d86a13e92ccd02805 }}/backend:${{ github.sha }}'